spring:
  application:
    name: dubbo-demo-provider

dubbo:
  application:
    name: ${spring.application.name}
    qos-port: 22222
  protocol:
    name: tri
    port: -1
  registry:
    address: nacos://127.0.0.1:8848?username=nacos&password=7fDJZBbiLzO2
    register-mode: instance
  config-center:
    address: nacos://127.0.0.1:8848?username=nacos&password=7fDJZBbiLzO2
  metadata-report:
    address: nacos://127.0.0.1:8848?username=nacos&password=7fDJZBbiLzO2
  tracing:
    enabled: true

sentinel:
  nacos:
    server-addr: 127.0.0.1:8848
    username: nacos
    password: 7fDJZBbiLzO2
    flow:
      group-id: SENTINEL_GROUP
      data-id: dubbo.demo.provider.flow.rules
