server:
  port: 8761

nacos:
  server-addr: 127.0.0.1:8848
  username: nacos
  password: 7fDJZBbiLzO2

spring:
  application:
    name: whatsmars-nacos
  nacos:
    config:
      server-addr: ${nacos.server-addr}
    username: ${nacos.username}
    password: ${nacos.password}
  config:
    import:
      - nacos:cloud-agent.properties?refreshEnabled=true&group=DEFAULT_GROUP