server:
  port: 8081

spring:
  application:
    name: whatsmars-ai-alibaba
  ai:
    dashscope:
      api-key: ${DASHSCOPE_API_KEY}
      chat:
        options:
          model: qwen-plus
    mcp:
      client:
        enabled: true
        type: SYNC
        sse:
          connections:
            whatsmars-ai-spring:
              url: http://localhost:8083/sse
