spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: root
    password: test
    schema: classpath:db/schema-h2.sql
    data: classpath:db/data-h2.sql

logging:
  level:
    com.baomidou.mybatisplus.samples.quickstart: debug
